# Generated by Django 5.2.5 on 2025-08-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='domain',
            field=models.CharField(blank=True, choices=[('java', 'Java'), ('python', 'Python'), ('web_developer', 'Web Developer'), ('testing', 'Testing'), ('devops', 'DevOps'), ('powerbi', 'Power BI')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
