# Generated by Django 5.2.5 on 2025-08-10 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_customuser_domain_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('java', 'Java'), ('python', 'Python'), ('web_developer', 'Web Developer'), ('testing', 'Testing'), ('devops', 'DevOps'), ('powerbi', 'Power BI')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_trained', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
