# Generated by Django 5.2.5 on 2025-08-11 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='name',
            new_name='batchname',
        ),
    ]
