# Generated by Django 5.2.5 on 2025-08-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trainee',
            name='trainername',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
