# Generated by Django 5.2.5 on 2025-08-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_trainee_domain_trainee_trainername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='trainername',
            field=models.CharField(max_length=100),
        ),
    ]
