# Generated by Django 5.2.5 on 2025-09-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_assignmenttype_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='trainee',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assignments', to='firstapp.batch'),
        ),
    ]
